name: Deploy Static Website to Azure

on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload Files to Storage
      run: |
        az storage blob upload-batch \
        --account-name jamiustaticwebsitestore \
        --destination '$web' \
        --source .